service: http-proxy-lambda

provider:
  name: aws

functions:
  http-proxy-lambda:
    runtime: haskell
    handler: http-proxy-lambda.proxy
    events:
     - http:
        path: endpoint/{url}
        method: get
        cors: true
  home:
    runtime: nodejs8.10
    handler: frontend/index.handler
    events:
     - http:
        path: home
        method: get
        cors: true
  render:
    runtime: haskell
    handler: http-proxy-lambda.render
    events:
     - http:
        path: render
        method: get
        cors: true

plugins:
  - serverless-haskell
